name: First Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: | 
          echo 'Hello world!'
          echo Hello, $USER

      - name: Print work directory
        run: pwd

#  second-job:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Grand gradlew file
#        run: chmod +x api/gradlew
#
#      -name: Run tests