name: Issue printing
on: issues

jobs:
  show-issue-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue
        run: |
          echo ${{ github.event.issue.title }}
          echo ${{ github.event.issue.description }}