name: Test Project
on:
  push:
    branches:
      - 'master'

#or can be written as:
#on: push
#just without specifying branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6

      - name: Set Up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'termium'
          java-version: '21'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Grant authorise for Gradlew
        run: chmod +x ./api/gradlew

      - name: Run tests
        run: ./api/gradlew -p api clean test
